### ISSUE TITLE
Subscribe to my youtube channel for windows 12 leak

### ISSUE THREAD

**Issue by Zane2b2t** [HAV0X1014/Pingbypass-Road-Warrior-Installer#2]
but fr people now might not care but later littile kids will dig into pingbypass and stumble across this

**Comment by HAV0X1014** [comment]
big if true

**Comment by Zane2b2t** [comment]
> 

WHY IS GITHUB GLITCHING MAKING STUFF I SENT 5 MINUTES AGO SAY 12 HOURS AGO THIS HAS HAPPEND 14 TIMES NOW

**Comment by Zane2b2t** [comment]
> > 
> 
> WHY IS GITHUB GLITCHING MAKING STUFF I SENT 5 MINUTES AGO SAY 12 HOURS AGO THIS HAS HAPPEND 14 TIMES NOW

15 now cus of this comment and 16 bcs of this one
